#!/system/bin/sh
# version 1.0

#Create logfile
if [ ! -e /sdcard/vconf.log ] ;then
    touch /sdcard/vconf.log
fi
echo "" >> /sdcard/vconf.log
echo "`date +%Y-%m-%d_%T` Device rebooted" >> /sdcard/vconf.log

# execute vmapper.sh
sh -x /system/bin/vmapper.sh -ua
